// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anraft/proto/peer_proto/peer.proto

package peer_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerState int32

const (
	PeerState_Follower  PeerState = 0
	PeerState_Candidate PeerState = 1
	PeerState_Leader    PeerState = 2
)

var PeerState_name = map[int32]string{
	0: "Follower",
	1: "Candidate",
	2: "Leader",
}
var PeerState_value = map[string]int32{
	"Follower":  0,
	"Candidate": 1,
	"Leader":    2,
}

func (x PeerState) String() string {
	return proto.EnumName(PeerState_name, int32(x))
}
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_peer_caca4900cca21338, []int{0}
}

type ReqHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Seqid                int64    `protobuf:"varint,3,opt,name=seqid,proto3" json:"seqid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_caca4900cca21338, []int{0}
}
func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (dst *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(dst, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReqHeader) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

type ResHeader struct {
	Seqid                int64    `protobuf:"varint,1,opt,name=seqid,proto3" json:"seqid,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,4,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHeader) Reset()         { *m = ResHeader{} }
func (m *ResHeader) String() string { return proto.CompactTextString(m) }
func (*ResHeader) ProtoMessage()    {}
func (*ResHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_caca4900cca21338, []int{1}
}
func (m *ResHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHeader.Unmarshal(m, b)
}
func (m *ResHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHeader.Marshal(b, m, deterministic)
}
func (dst *ResHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHeader.Merge(dst, src)
}
func (m *ResHeader) XXX_Size() int {
	return xxx_messageInfo_ResHeader.Size(m)
}
func (m *ResHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResHeader proto.InternalMessageInfo

func (m *ResHeader) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *ResHeader) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ResHeader) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

type HeartBeatReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_caca4900cca21338, []int{2}
}
func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (dst *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(dst, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type HeartBeatRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HeartBeatRes) Reset()         { *m = HeartBeatRes{} }
func (m *HeartBeatRes) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRes) ProtoMessage()    {}
func (*HeartBeatRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_caca4900cca21338, []int{3}
}
func (m *HeartBeatRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRes.Unmarshal(m, b)
}
func (m *HeartBeatRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRes.Marshal(b, m, deterministic)
}
func (dst *HeartBeatRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRes.Merge(dst, src)
}
func (m *HeartBeatRes) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRes.Size(m)
}
func (m *HeartBeatRes) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRes.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRes proto.InternalMessageInfo

func (m *HeartBeatRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqHeader)(nil), "peer_proto.ReqHeader")
	proto.RegisterType((*ResHeader)(nil), "peer_proto.ResHeader")
	proto.RegisterType((*HeartBeatReq)(nil), "peer_proto.HeartBeatReq")
	proto.RegisterType((*HeartBeatRes)(nil), "peer_proto.HeartBeatRes")
	proto.RegisterEnum("peer_proto.PeerState", PeerState_name, PeerState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerClient interface {
	HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRes, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) HeartBeat(ctx context.Context, in *HeartBeatReq, opts ...grpc.CallOption) (*HeartBeatRes, error) {
	out := new(HeartBeatRes)
	err := c.cc.Invoke(ctx, "/peer_proto.Peer/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
type PeerServer interface {
	HeartBeat(context.Context, *HeartBeatReq) (*HeartBeatRes, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peer_proto.Peer/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).HeartBeat(ctx, req.(*HeartBeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "peer_proto.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _Peer_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anraft/proto/peer_proto/peer.proto",
}

func init() {
	proto.RegisterFile("anraft/proto/peer_proto/peer.proto", fileDescriptor_peer_caca4900cca21338)
}

var fileDescriptor_peer_caca4900cca21338 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbf, 0xdb, 0x1f, 0xf9, 0x36, 0x63, 0x85, 0x32, 0x28, 0xae, 0x9e, 0x42, 0x4e, 0x41,
	0x30, 0x85, 0xea, 0x4d, 0x44, 0xb0, 0xa0, 0x3d, 0x28, 0xc8, 0x8a, 0xe7, 0xb0, 0xba, 0x63, 0x0d,
	0xd4, 0x6c, 0x33, 0xbb, 0xe8, 0xbf, 0x2f, 0x49, 0x6b, 0x12, 0x05, 0xf1, 0xf6, 0x66, 0xf6, 0x7d,
	0xe6, 0xed, 0x83, 0x58, 0x17, 0xac, 0x5f, 0xfc, 0x74, 0xcd, 0xd6, 0xdb, 0xe9, 0x9a, 0x88, 0xb3,
	0x56, 0xa6, 0xb5, 0x44, 0x68, 0xd7, 0xf1, 0x39, 0x84, 0x8a, 0xca, 0x05, 0x69, 0x43, 0x8c, 0x12,
	0xfe, 0xbf, 0x13, 0xbb, 0xdc, 0x16, 0x52, 0x44, 0x22, 0x19, 0xaa, 0xaf, 0x11, 0xf7, 0x60, 0xe8,
	0xa8, 0xcc, 0x8d, 0xec, 0x47, 0x22, 0xe9, 0xab, 0xcd, 0x10, 0x3f, 0x56, 0xb0, 0xdb, 0xc2, 0x8d,
	0x45, 0x74, 0x2c, 0x78, 0x08, 0x23, 0x26, 0x9f, 0x3d, 0x5b, 0x43, 0xb2, 0xb7, 0xb9, 0xc9, 0xe4,
	0xe7, 0xd6, 0x10, 0x1e, 0x40, 0x25, 0xb3, 0x37, 0xb7, 0x94, 0x83, 0x48, 0x24, 0xa1, 0x0a, 0x98,
	0xfc, 0x9d, 0x5b, 0xc6, 0x17, 0x30, 0x5e, 0x90, 0x66, 0x7f, 0x45, 0xda, 0x2b, 0x2a, 0xf1, 0x04,
	0x82, 0xd7, 0x3a, 0xa3, 0x3e, 0xbd, 0x33, 0xdb, 0x4f, 0xdb, 0x02, 0x69, 0xf3, 0x7b, 0xb5, 0x35,
	0xfd, 0xc0, 0xdd, 0x5f, 0xb8, 0xfb, 0x8e, 0x1f, 0x9f, 0x41, 0x78, 0x4f, 0xc4, 0x0f, 0x5e, 0x7b,
	0xc2, 0x31, 0x8c, 0xae, 0xed, 0x6a, 0x65, 0x3f, 0x88, 0x27, 0xff, 0x70, 0x17, 0xc2, 0xb9, 0x2e,
	0x4c, 0x6e, 0xb4, 0xa7, 0x89, 0x40, 0x80, 0xe0, 0xb6, 0x66, 0x26, 0xbd, 0xd9, 0x0d, 0x0c, 0x2a,
	0x0a, 0x2f, 0x21, 0x6c, 0xc2, 0x51, 0x76, 0x93, 0xba, 0x95, 0x8e, 0x7e, 0x7b, 0x71, 0x4f, 0x41,
	0xbd, 0x3b, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x97, 0xcf, 0xfc, 0xc9, 0x01, 0x00, 0x00,
}
