// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anraft/proto/peer_proto/peer.proto

package peer_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerState int32

const (
	PeerState_Follower  PeerState = 0
	PeerState_Candidate PeerState = 1
	PeerState_Leader    PeerState = 2
)

var PeerState_name = map[int32]string{
	0: "Follower",
	1: "Candidate",
	2: "Leader",
}
var PeerState_value = map[string]int32{
	"Follower":  0,
	"Candidate": 1,
	"Leader":    2,
}

func (x PeerState) String() string {
	return proto.EnumName(PeerState_name, int32(x))
}
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{0}
}

type LogOp int32

const (
	LogOp_Set LogOp = 0
	LogOp_Del LogOp = 1
)

var LogOp_name = map[int32]string{
	0: "Set",
	1: "Del",
}
var LogOp_value = map[string]int32{
	"Set": 0,
	"Del": 1,
}

func (x LogOp) String() string {
	return proto.EnumName(LogOp_name, int32(x))
}
func (LogOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{1}
}

type ReqHeader struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Seqid                int64    `protobuf:"varint,3,opt,name=seqid,proto3" json:"seqid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{0}
}
func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (dst *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(dst, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReqHeader) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

type ResHeader struct {
	Seqid                int64    `protobuf:"varint,1,opt,name=seqid,proto3" json:"seqid,omitempty"`
	RetCode              int32    `protobuf:"varint,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	RetMsg               string   `protobuf:"bytes,4,opt,name=ret_msg,json=retMsg,proto3" json:"ret_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHeader) Reset()         { *m = ResHeader{} }
func (m *ResHeader) String() string { return proto.CompactTextString(m) }
func (*ResHeader) ProtoMessage()    {}
func (*ResHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{1}
}
func (m *ResHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHeader.Unmarshal(m, b)
}
func (m *ResHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHeader.Marshal(b, m, deterministic)
}
func (dst *ResHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHeader.Merge(dst, src)
}
func (m *ResHeader) XXX_Size() int {
	return xxx_messageInfo_ResHeader.Size(m)
}
func (m *ResHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResHeader proto.InternalMessageInfo

func (m *ResHeader) GetSeqid() int64 {
	if m != nil {
		return m.Seqid
	}
	return 0
}

func (m *ResHeader) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func (m *ResHeader) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

type RequestVoteReq struct {
	Header               *ReqHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 int64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          string     `protobuf:"bytes,3,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex         int64      `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm          int64      `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestVoteReq) Reset()         { *m = RequestVoteReq{} }
func (m *RequestVoteReq) String() string { return proto.CompactTextString(m) }
func (*RequestVoteReq) ProtoMessage()    {}
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{2}
}
func (m *RequestVoteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteReq.Unmarshal(m, b)
}
func (m *RequestVoteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteReq.Marshal(b, m, deterministic)
}
func (dst *RequestVoteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteReq.Merge(dst, src)
}
func (m *RequestVoteReq) XXX_Size() int {
	return xxx_messageInfo_RequestVoteReq.Size(m)
}
func (m *RequestVoteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteReq proto.InternalMessageInfo

func (m *RequestVoteReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RequestVoteReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteReq) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteReq) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteReq) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 int64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted          string     `protobuf:"bytes,3,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RequestVoteRes) Reset()         { *m = RequestVoteRes{} }
func (m *RequestVoteRes) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRes) ProtoMessage()    {}
func (*RequestVoteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{3}
}
func (m *RequestVoteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRes.Unmarshal(m, b)
}
func (m *RequestVoteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRes.Marshal(b, m, deterministic)
}
func (dst *RequestVoteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRes.Merge(dst, src)
}
func (m *RequestVoteRes) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRes.Size(m)
}
func (m *RequestVoteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRes.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRes proto.InternalMessageInfo

func (m *RequestVoteRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RequestVoteRes) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRes) GetVoteGranted() string {
	if m != nil {
		return m.VoteGranted
	}
	return ""
}

type LogEntry struct {
	Index                int64    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term                 int64    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Op                   LogOp    `protobuf:"varint,3,opt,name=op,proto3,enum=peer_proto.LogOp" json:"op,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{4}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (dst *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(dst, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetOp() LogOp {
	if m != nil {
		return m.Op
	}
	return LogOp_Set
}

func (m *LogEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LogEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AppendEntriesReq struct {
	Header               *ReqHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 int64       `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             string      `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex         int64       `protobuf:"varint,4,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm          int64       `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries              []*LogEntry `protobuf:"bytes,6,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         int64       `protobuf:"varint,7,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AppendEntriesReq) Reset()         { *m = AppendEntriesReq{} }
func (m *AppendEntriesReq) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesReq) ProtoMessage()    {}
func (*AppendEntriesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{5}
}
func (m *AppendEntriesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesReq.Unmarshal(m, b)
}
func (m *AppendEntriesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesReq.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesReq.Merge(dst, src)
}
func (m *AppendEntriesReq) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesReq.Size(m)
}
func (m *AppendEntriesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesReq.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesReq proto.InternalMessageInfo

func (m *AppendEntriesReq) GetHeader() *ReqHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AppendEntriesReq) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReq) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntriesReq) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesReq) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesReq) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntriesReq) GetLeaderCommit() int64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntriesRes struct {
	Header               *ResHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 int64      `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Result               int32      `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	Msg                  string     `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppendEntriesRes) Reset()         { *m = AppendEntriesRes{} }
func (m *AppendEntriesRes) String() string { return proto.CompactTextString(m) }
func (*AppendEntriesRes) ProtoMessage()    {}
func (*AppendEntriesRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_peer_1331139b65a4174f, []int{6}
}
func (m *AppendEntriesRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntriesRes.Unmarshal(m, b)
}
func (m *AppendEntriesRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntriesRes.Marshal(b, m, deterministic)
}
func (dst *AppendEntriesRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntriesRes.Merge(dst, src)
}
func (m *AppendEntriesRes) XXX_Size() int {
	return xxx_messageInfo_AppendEntriesRes.Size(m)
}
func (m *AppendEntriesRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntriesRes.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntriesRes proto.InternalMessageInfo

func (m *AppendEntriesRes) GetHeader() *ResHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AppendEntriesRes) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRes) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *AppendEntriesRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqHeader)(nil), "peer_proto.ReqHeader")
	proto.RegisterType((*ResHeader)(nil), "peer_proto.ResHeader")
	proto.RegisterType((*RequestVoteReq)(nil), "peer_proto.RequestVoteReq")
	proto.RegisterType((*RequestVoteRes)(nil), "peer_proto.RequestVoteRes")
	proto.RegisterType((*LogEntry)(nil), "peer_proto.LogEntry")
	proto.RegisterType((*AppendEntriesReq)(nil), "peer_proto.AppendEntriesReq")
	proto.RegisterType((*AppendEntriesRes)(nil), "peer_proto.AppendEntriesRes")
	proto.RegisterEnum("peer_proto.PeerState", PeerState_name, PeerState_value)
	proto.RegisterEnum("peer_proto.LogOp", LogOp_name, LogOp_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PeerClient interface {
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error)
	AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesRes, error)
}

type peerClient struct {
	cc *grpc.ClientConn
}

func NewPeerClient(cc *grpc.ClientConn) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteRes, error) {
	out := new(RequestVoteRes)
	err := c.cc.Invoke(ctx, "/peer_proto.Peer/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesRes, error) {
	out := new(AppendEntriesRes)
	err := c.cc.Invoke(ctx, "/peer_proto.Peer/AppendEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
type PeerServer interface {
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteRes, error)
	AppendEntries(context.Context, *AppendEntriesReq) (*AppendEntriesRes, error)
}

func RegisterPeerServer(s *grpc.Server, srv PeerServer) {
	s.RegisterService(&_Peer_serviceDesc, srv)
}

func _Peer_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peer_proto.Peer/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/peer_proto.Peer/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).AppendEntries(ctx, req.(*AppendEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Peer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "peer_proto.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Peer_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Peer_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anraft/proto/peer_proto/peer.proto",
}

func init() {
	proto.RegisterFile("anraft/proto/peer_proto/peer.proto", fileDescriptor_peer_1331139b65a4174f)
}

var fileDescriptor_peer_1331139b65a4174f = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xad, 0xe3, 0xc6, 0x89, 0x27, 0x49, 0xe5, 0x6f, 0xd4, 0x0f, 0xdc, 0xc2, 0x21, 0x18, 0x0e,
	0x51, 0x25, 0x52, 0x29, 0x70, 0xe3, 0x84, 0x4a, 0x81, 0x8a, 0x20, 0xd0, 0x16, 0xb8, 0x5a, 0x26,
	0x1e, 0x8c, 0x85, 0xe3, 0x75, 0x76, 0x37, 0x81, 0x9e, 0xfa, 0x1b, 0xb8, 0xf2, 0x6b, 0xf8, 0x69,
	0x68, 0xd7, 0x8e, 0x63, 0x52, 0x15, 0x38, 0xf4, 0x36, 0xf3, 0xf6, 0xed, 0xec, 0xbc, 0x79, 0xb3,
	0x10, 0x44, 0xb9, 0x88, 0x3e, 0xa9, 0xe3, 0x42, 0x70, 0xc5, 0x8f, 0x0b, 0x22, 0x11, 0x6e, 0xc2,
	0xb1, 0x09, 0x11, 0x36, 0x70, 0xf0, 0x04, 0x5c, 0x46, 0x8b, 0x97, 0x14, 0xc5, 0x24, 0xd0, 0x87,
	0xce, 0x8a, 0x84, 0x4c, 0x79, 0xee, 0x5b, 0x43, 0x6b, 0xd4, 0x66, 0xeb, 0x14, 0xf7, 0xa1, 0x2d,
	0x69, 0x91, 0xc6, 0xbe, 0x3d, 0xb4, 0x46, 0x36, 0x2b, 0x93, 0xe0, 0xbd, 0xbe, 0x2c, 0xab, 0xcb,
	0x35, 0xc5, 0x6a, 0x50, 0xf0, 0x00, 0xba, 0x82, 0x54, 0x38, 0xe3, 0x31, 0xf9, 0xad, 0xb2, 0xa6,
	0x20, 0x75, 0xc2, 0x63, 0xc2, 0xdb, 0xa0, 0xc3, 0x70, 0x2e, 0x13, 0x7f, 0x77, 0x68, 0x8d, 0x5c,
	0xe6, 0x08, 0x52, 0xaf, 0x65, 0x12, 0xfc, 0xb4, 0x60, 0x8f, 0xd1, 0x62, 0x49, 0x52, 0x7d, 0xe0,
	0x8a, 0x18, 0x2d, 0xf0, 0x21, 0x38, 0x9f, 0xcd, 0x33, 0xa6, 0x7a, 0x6f, 0xf2, 0xff, 0x78, 0xa3,
	0x61, 0x5c, 0x0b, 0x60, 0x15, 0x09, 0x11, 0x76, 0x15, 0x89, 0xb9, 0x79, 0xd1, 0x66, 0x26, 0xc6,
	0x7b, 0xd0, 0x9f, 0x45, 0x79, 0x9c, 0xc6, 0x91, 0xa2, 0xb0, 0x52, 0xe2, 0xb2, 0x5e, 0x8d, 0x9d,
	0xc5, 0xf8, 0x00, 0xf6, 0xb2, 0x48, 0xaa, 0x30, 0xe3, 0x49, 0x98, 0xe6, 0x31, 0x7d, 0x33, 0x8d,
	0xd9, 0xac, 0xaf, 0xd1, 0x29, 0x4f, 0xce, 0x34, 0x86, 0x01, 0x0c, 0x6a, 0x96, 0x79, 0xa5, 0x6d,
	0x48, 0xbd, 0x8a, 0xf4, 0x8e, 0xc4, 0x3c, 0x58, 0x6d, 0x29, 0x90, 0x7f, 0x53, 0x20, 0xff, 0x4d,
	0xc1, 0x8a, 0x2b, 0x0a, 0x13, 0x11, 0xe5, 0x8a, 0x6a, 0x05, 0x1a, 0x7b, 0x51, 0x42, 0xc1, 0x25,
	0x74, 0xa7, 0x3c, 0x39, 0xcd, 0x95, 0xb8, 0xd0, 0x86, 0x94, 0x22, 0x2a, 0x43, 0x4c, 0x72, 0x4d,
	0xe1, 0x16, 0x2f, 0x4c, 0xb9, 0xbd, 0xc9, 0x7f, 0xcd, 0xbe, 0xa6, 0x3c, 0x79, 0x53, 0xb0, 0x16,
	0x2f, 0xd0, 0x03, 0xfb, 0x0b, 0x5d, 0x54, 0x46, 0xe9, 0x50, 0x97, 0x5f, 0x45, 0xd9, 0x92, 0x8c,
	0xfc, 0x3e, 0x2b, 0x93, 0xe0, 0x7b, 0x0b, 0xbc, 0xa7, 0x45, 0x41, 0x79, 0xac, 0x9b, 0x48, 0x49,
	0xde, 0x90, 0x7b, 0x77, 0xc0, 0xcd, 0xcc, 0xe9, 0xc6, 0xba, 0x6e, 0x09, 0x94, 0xbe, 0x15, 0x82,
	0x56, 0x57, 0x7d, 0xd3, 0x68, 0xd3, 0xb7, 0x9a, 0xd5, 0xf4, 0xad, 0x22, 0x69, 0xdf, 0x70, 0x0c,
	0x1d, 0x2a, 0xfb, 0xf6, 0x9d, 0xa1, 0x3d, 0xea, 0x4d, 0xf6, 0xb7, 0xc6, 0x61, 0x46, 0xcb, 0xd6,
	0x24, 0xbc, 0x0f, 0x83, 0xaa, 0xad, 0x19, 0x9f, 0xcf, 0x53, 0xe5, 0x77, 0xaa, 0x85, 0x31, 0xe0,
	0x89, 0xc1, 0x82, 0xcb, 0x2b, 0x23, 0xb9, 0x91, 0x75, 0xb8, 0x05, 0x8e, 0x20, 0xb9, 0xcc, 0x94,
	0x99, 0x47, 0x9b, 0x55, 0x99, 0xb6, 0x6a, 0xf3, 0xa7, 0x74, 0x78, 0xf4, 0x18, 0xdc, 0xb7, 0x44,
	0xe2, 0x5c, 0x45, 0x8a, 0xb0, 0x0f, 0xdd, 0xe7, 0x3c, 0xcb, 0xf8, 0x57, 0x12, 0xde, 0x0e, 0x0e,
	0xc0, 0x3d, 0x59, 0xff, 0x00, 0xcf, 0x42, 0x00, 0x67, 0x6a, 0x5e, 0xf4, 0x5a, 0x47, 0x07, 0xd0,
	0x36, 0xfe, 0x63, 0x07, 0xec, 0x73, 0x52, 0xde, 0x8e, 0x0e, 0x9e, 0x51, 0xe6, 0x59, 0x93, 0x1f,
	0x16, 0xec, 0xea, 0x8a, 0x78, 0x0a, 0xbd, 0xc6, 0x9e, 0xe3, 0xe1, 0x96, 0xb1, 0x8d, 0x2f, 0x7c,
	0x78, 0xfd, 0x99, 0xc4, 0x57, 0x30, 0xf8, 0x6d, 0x42, 0x78, 0xb7, 0x49, 0xde, 0xde, 0xa7, 0xc3,
	0x3f, 0x9d, 0xca, 0x8f, 0x8e, 0xc1, 0x1f, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x13, 0x3a, 0xc8,
	0xf6, 0x0b, 0x05, 0x00, 0x00,
}
